name = "Amperage"

license = "MIT"
licenselink = "https://github.com/asurbernardo/amperage/blob/master/LICENSE"

description = "⚡ A GoHugo blog theme, minimal yet feature loaded with AMP, service workers, structured data and more! ⚡"

homepage = "https://github.com/asurbernardo/amperage"

tags = ["blog", "personal", "responsive", 'minimal', 'clean', "simple", "google analytics", "light",
    "minimal", "multilingual", "syntax highlighting", "fast", "customizable", "minimalistic",
    "technical", "amp"]

features = ["amp", "seo", "pwa", "structured data", "toc", "related content", "service-worker", "shortcodes",
    "syntax highlighting", "tags", "social share"]

min_version = "0.41"

[author]
    name = "Asur Bernardo"
    homepage = "https://asur.dev"
