name = "Amperage"
license = "MIT"
licenselink = "https://github.com/asurbernardo/amperage/blob/master/LICENSE"
description = "⚡ A GoHugo blog theme with AMP and other SEO goodies ⚡"
homepage = "https://github.com/asurbernardo/amperage"
tags = ["amp", "seo", "blog"]
features = ["amp", "seo", "toc", "related content", "structured data", "shortcodes"]
min_version = "0.41"

[author]
  name = "Asur Bernardo"
  homepage = "https://asurbernardo.com"
