name = "Amperage"

license = "MIT"
licenselink = "https://github.com/asurbernardo/amperage/blob/master/LICENSE"

description = "Blazing fast SEO optimized theme with native AMP, structured data, search, service workers and i18n out of the box!"

homepage = "https://github.com/asurbernardo/amperage"

tags = ["blog", "personal", "responsive", 'minimal', 'clean', "simple", "google analytics", "light",
    "multilingual", "syntax highlighting", "fast", "customizable", "minimalistic", "technical", "amp",
    "white", "disqus", "starter", "search"]

features = ["amp", "seo", "pwa", "responsive", "structured data", "toc", "related content", "service-worker", "shortcodes",
    "syntax highlighting", "tags", "social share", "search"]

min_version = "0.72.0"

[author]
    name = "Asur Bernardo"
    homepage = "https://asur.dev"
